# Generated by Django 2.2.4 on 2019-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salutation',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Salutation'),
        ),
    ]
