# Generated by Django 2.0.6 on 2018-06-23 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_common.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'Active'), ('closed', 'Closed'), ('inactive', 'Inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Related Context ID')),
                ('title', models.CharField(blank=True, help_text='Maximum 150 Characters', max_length=55, null=True)),
                ('description', models.CharField(blank=True, help_text='Maximum 200 Characters', max_length=150, null=True)),
                ('resource_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'Pdf'), ('audio', 'Audio'), ('video', 'Video')], max_length=7)),
                ('file', models.FileField(default='/media/defaults/resource-default.jpg', max_length=255, upload_to=django_common.utils.get_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(blank=True, max_length=40, null=True)),
                ('form_id', models.CharField(blank=True, max_length=40, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'organisation')), models.Q(('app_label', 'core'), ('model', 'channel')), models.Q(('app_label', 'core'), ('model', 'usercontext')), models.Q(('app_label', 'core'), ('model', 'sitewidecontext')), models.Q(('app_label', 'contexts'), ('model', 'project')), models.Q(('app_label', 'users'), ('model', 'user')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileresources_resource_related', to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
